spring:
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/hh_db
    user: root
    password: root
    change-log: db/change_log_master.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hh_db
    password: root
    username: root

server:
  port: 8080

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org:
      springframework:
        data:
          r2dbc=DEBUG:
